name: shadcn_flutter
description: "Beautifully designed components from Shadcn/UI is now available for Flutter"
version: 0.0.36

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Icons
  bootstrap_icons: ^1.11.3
  lucide_icons_flutter: 
  # radix_icons: ^1.0.1


  email_validator: ^3.0.0
  skeletonizer: ^1.4.2
  syntax_highlight: ^0.4.0
  country_flags: ^3.0.0
  phonecodes: ^0.0.3
  cross_file: ^0.3.4+2
  image: ^4.2.0
  web: ^1.0.0
  data_widget: ^0.0.2
  gap: ^3.0.1
  expressions: ^0.2.5+2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  archive: any
  icon_font_generator: ^4.0.0



flutter:
  uses-material-design: true