name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.29.0'
          channel: 'stable' 

      - name: Enable Flutter Web
        run: flutter config --enable-web
        working-directory: './docs'

      - name: Download Dependencies
        run: flutter pub get
        working-directory: './docs'

      - name: Build
        run: "flutter build web --wasm --base-href \"/shadcn_flutter/\""
        working-directory: './docs'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './docs/build/web'
          force_orphan: true
          user_name: 'github-ci[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Publish to gh-pages'
